Eventos.IO/src/Eventos.IO.Site/Controllers/EventosController.cs
using Eventos.IO.Application.Interfaces;
using Eventos.IO.Application.ViewModels;
using Eventos.IO.Domain.Core.Notifications;
using Eventos.IO.Domain.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;

namespace Eventos.IO.Site.Controllers
{
	[Route("")]
	public class EventosController : BaseController
	{
		private readonly IEventoAppService _eventoAppService;

		public EventosController(IEventoAppService eventoAppService,
								 IDomainNotificationHandler<DomainNotification> notifications, IUser user) : base(notifications, user)
		{
			_eventoAppService = eventoAppService;
		}

		[Route("")]
		[Route("proximos-eventos")]
		public IActionResult Index()
		{
			return View(_eventoAppService.ObterTodos());
		}

		[Route("meus-eventos")]
		[Authorize(Policy = "PodeLerEventos")]
		public IActionResult MeusEventos()
		{
			return View(_eventoAppService.ObterEventoPorOrganizador(OrganizadorId));
		}

		[Route("dados-do-evento/{id:guid}")]
		public IActionResult Details(Guid? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			EventoViewModel eventoViewModel = _eventoAppService.ObterPorId(id.Value);
			if (eventoViewModel == null)
			{
				return NotFound();
			}

			return View(eventoViewModel);
		}

		[Route("novo-evento")]
		[Authorize(Policy = "PodeGravar")]
		public IActionResult Create()
		{
			return View();
		}

		[Route("novo-evento")]
		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize(Policy = "PodeGravar")]
		public IActionResult Create(EventoViewModel eventoViewModel)
		{
			if (!ModelState.IsValid)
			{
				return View(eventoViewModel);
			}

			eventoViewModel.OrganizadorId = OrganizadorId;

			_eventoAppService.Registrar(eventoViewModel);

			ViewBag.RetornoPost = OperacaoValida() ? "success,Evento Registrado com Sucesso!" :
				"error,Evento não Registrado! Verifique as Mensagens";

			return View(eventoViewModel);
		}

		[Route("editar-evento/{id:guid}")]
		[Authorize(Policy = "PodeGravar")]
		public IActionResult Edit(Guid? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			EventoViewModel eventoViewModel = _eventoAppService.ObterPorId(id.Value);

			if (eventoViewModel == null)
			{
				return NotFound();
			}

			if (ValidarAutoridadeEvento(eventoViewModel))
			{
				return RedirectToAction("MeusEventos", _eventoAppService.ObterEventoPorOrganizador(OrganizadorId));
			}
			
			return View(eventoViewModel);
		}

		[Route("editar-evento/{id:guid}")]
		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize(Policy = "PodeGravar")]
		public IActionResult Edit(EventoViewModel eventoViewModel)
		{
			if (ValidarAutoridadeEvento(eventoViewModel))
			{
				return RedirectToAction("MeusEventos", _eventoAppService.ObterEventoPorOrganizador(OrganizadorId));
			}

			if (!ModelState.IsValid) return View(eventoViewModel);

			eventoViewModel.OrganizadorId = OrganizadorId;

			_eventoAppService.Atualizar(eventoViewModel);

			ViewBag.RetornoPost = OperacaoValida() ? "success,Evento Atualizado com Sucesso!" :
				"error,Evento não pode ser Atualizado! Verifique as Mensagens";

			if (_eventoAppService.ObterPorId(eventoViewModel.Id).Online)
			{
				eventoViewModel.Endereco = null;
			}
			else
			{
				eventoViewModel = _eventoAppService.ObterPorId(eventoViewModel.Id);
			}

			return View(eventoViewModel);
		}

		[Route("excluir-evento/{id:guid}")]
		[Authorize(Policy = "PodeGravar")]
		public IActionResult Delete(Guid? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			EventoViewModel eventoViewModel = _eventoAppService.ObterPorId(id.Value);

			if (eventoViewModel == null)
			{
				return NotFound();
			}

			if (ValidarAutoridadeEvento(eventoViewModel))
			{
				return RedirectToAction("MeusEventos", _eventoAppService.ObterEventoPorOrganizador(OrganizadorId));
			}

			return View(eventoViewModel);
		}

		[Route("excluir-evento/{id:guid}")]
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		[Authorize(Policy = "PodeGravar")]
		public IActionResult DeleteConfirmed(Guid id)
		{

			if (ValidarAutoridadeEvento(_eventoAppService.ObterPorId(id)))
			{
				return RedirectToAction("MeusEventos", _eventoAppService.ObterEventoPorOrganizador(OrganizadorId));
			}

			_eventoAppService.Excluir(id);

			return RedirectToAction("Index");
		}

		[Route("incluir-endereco/{id:guid}")]
		[Authorize(Policy = "PodeGravar")]
		public IActionResult IncluirEndereco(Guid? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			EventoViewModel eventoViewModel = _eventoAppService.ObterPorId(id.Value);

			return PartialView("_IncluirEndereco", eventoViewModel);
		}	

		[Route("incluir-endereco/{id:guid}")]
		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize(Policy = "PodeGravar")]
		public IActionResult IncluirEndereco(EventoViewModel eventoViewModel)
		{
			ModelState.Clear();

			eventoViewModel.Endereco.EventoId = eventoViewModel.Id;

			_eventoAppService.AdicionarEndereco(eventoViewModel.Endereco);

			if (OperacaoValida())
			{
				string url = Url.Action("ObterEndereco", "Eventos", new { id = eventoViewModel.Id });

				return Json(new { success = true, url = url });
			}

			return PartialView("_IncluirEndereco", eventoViewModel);
		}

		[Route("atualizar-endereco/{id:guid}")]
		[Authorize(Policy = "PodeGravar")]
		public IActionResult AtualizarEndereco(Guid? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			EventoViewModel eventoViewModel = _eventoAppService.ObterPorId(id.Value);

			return PartialView("_AtualizarEndereco", eventoViewModel);
		}

		[Route("atualizar-endereco/{id:guid}")]
		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize(Policy = "PodeGravar")]
		public IActionResult AtualizarEndereco(EventoViewModel eventoViewModel)
		{
			ModelState.Clear();

			_eventoAppService.AtualizarEndereco(eventoViewModel.Endereco);

			if (OperacaoValida())
			{
				string url = Url.Action("ObterEndereco", "Eventos", new { id = eventoViewModel.Id });

				return Json(new { success = true, url = url });
			}

			return PartialView("_AtualizarEndereco", eventoViewModel);
		}

		[Route("listar-endereco/{id:guid}")]
		public IActionResult ObterEndereco(Guid id)
		{
			return PartialView("_DetalhesEndereco", _eventoAppService.ObterPorId(id));
		}

		private bool ValidarAutoridadeEvento(EventoViewModel eventoViewModel)
		{
			return eventoViewModel.OrganizadorId != OrganizadorId;
		}
	}
}

Eventos.IO/src/Eventos.IO.Site/ViewComponents/SummaryViewComponent.cs
using System.Threading.Tasks;
using Eventos.IO.Domain.Core.Notifications;
using Microsoft.AspNetCore.Mvc;

namespace Eventos.IO.Site.ViewComponents
{
	public class SummaryViewComponent : ViewComponent
	{
		private readonly IDomainNotificationHandler<DomainNotification> _notifications;

		public SummaryViewComponent(IDomainNotificationHandler<DomainNotification> notifications)
		{
			_notifications = notifications;
		}

		public async Task<IViewComponentResult> InvokeAsync()
		{
			var notificacoes = await Task.FromResult(_notifications.GetNotifications());

			notificacoes.ForEach(c => ViewData.ModelState.AddModelError(string.Empty, c.Value));

			return View();
		}
	}
}

Eventos.IO/src/Eventos.IO.Site/Views/Eventos/Create.cshtml
@model Eventos.IO.Application.ViewModels.EventoViewModel

@{
    ViewData["Title"] = "Registrar Novo Evento";
}

<h2>@ViewData["Title"]</h2>

<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.css" rel="stylesheet">

<h4>Preencha todos os dados corretamente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">

            <vc:summary></vc:summary>

            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="DescricaoCurta" class="control-label"></label>
                <input asp-for="DescricaoCurta" class="form-control" />
                <span asp-validation-for="DescricaoCurta" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="DescricaoLonga" class="control-label"></label>
                <textarea rows="5" asp-for="DescricaoLonga" class="form-control"></textarea>
                <span asp-validation-for="DescricaoLonga" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Categoria" class="control-label"></label>
                @Html.Partial("_Categorias")
                <span asp-validation-for="Categoria" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="DataInicio" class="control-label"></label>
                <input asp-for="DataInicio" type="text" class="form-control" />
                <span asp-validation-for="DataInicio" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="DataFim" class="control-label"></label>
                <input asp-for="DataFim" type="text" class="form-control" />
                <span asp-validation-for="DataFim" class="text-danger"></span>
            </div>

            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="Gratuito" /> @Html.DisplayNameFor(model => model.Gratuito)
                    </label>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Valor" class="control-label"></label>
                <input data-val-number="O Valor está em Formato Inválido" asp-for="Valor" class="form-control" />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>

            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="Online" /> @Html.DisplayNameFor(model => model.Online)
                    </label>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="NomeEmpresa" class="control-label"></label>
                <input asp-for="NomeEmpresa" class="form-control" />
                <span asp-validation-for="NomeEmpresa" class="text-danger"></span>
            </div>

            <div id="EnderecoForm">
                <hr />
                <h3>Endereço do Evento</h3>

                <div class="form-group">
                    <label asp-for="Endereco.Logradouro" class="control-label"></label>
                    <input asp-for="Endereco.Logradouro" class="form-control" />
                    <span asp-validation-for="Endereco.Logradouro" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Endereco.Numero" class="control-label"></label>
                    <input asp-for="Endereco.Numero" class="form-control" />
                    <span asp-validation-for="Endereco.Numero" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Endereco.Complemento" class="control-label"></label>
                    <input asp-for="Endereco.Complemento" class="form-control" />
                    <span asp-validation-for="Endereco.Complemento" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Endereco.Bairro" class="control-label"></label>
                    <input asp-for="Endereco.Bairro" class="form-control" />
                    <span asp-validation-for="Endereco.Bairro" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Endereco.Cep" class="control-label"></label>
                    <input asp-for="Endereco.Cep" class="form-control" />
                    <span asp-validation-for="Endereco.Cep" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Endereco.Cidade" class="control-label"></label>
                    <input asp-for="Endereco.Cidade" class="form-control" />
                    <span asp-validation-for="Endereco.Cidade" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Endereco.Estado" class="control-label"></label>
                    @Html.Partial("_Estados")
                    <span asp-validation-for="Endereco.Estado" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <input id="btSubmit" type="submit" value="Registrar" class="btn btn-success" />
                <a asp-action="MeusEventos" class="btn btn-info">Voltar para a Lista</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/locales/bootstrap-datepicker.pt-BR.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/locales/bootstrap-datepicker.pt.min.js"></script>

    <script>
        ValidacoesEvento();
    </script>

    @{
        if (ViewBag.RetornoPost != null)
        {
            var notificacao = ViewBag.RetornoPost.ToString().Split(',');

            <script>
                toastr["@notificacao[0]"]("@notificacao[1]");
            </script>

            if (@notificacao[0] == "success")
            {
                <script>
                    $("#btSubmit").prop("disabled", true);
                </script>
            }
        }
    }
}

Eventos.IO/src/Eventos.IO.Site/Views/Eventos/Delete.cshtml
@model Eventos.IO.Application.ViewModels.EventoViewModel

@{
    ViewData["Title"] = "Excluir Evento";
}

<h2>@ViewData["Title"]</h2>

<h3>Tem Certeza que deseja deletar esse Evento?</h3>
<div>
    <h4>Informação do Evento a ser excluido</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DescricaoCurta)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DescricaoCurta)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DescricaoLonga)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DescricaoLonga)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DataInicio)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DataInicio)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DataFim)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DataFim)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Gratuito)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Gratuito)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Online)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Online)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NomeEmpresa)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NomeEmpresa)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Categoria.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OrganizadorId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrganizadorId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> 
        <a asp-action="MeusEventos" class="btn btn-info">Voltar para a Lista</a>
    </form>
</div>

Eventos.IO/src/Eventos.IO.Site/Views/Eventos/Details.cshtml
@using Eventos.IO.Application.ViewModels
@model EventoViewModel

@{
    ViewData["Title"] = Model.Nome;
}

<div class="jumbotron">
    <h2>@ViewData["Title"]</h2>
    <h4>@Model.DescricaoCurta</h4>
</div>

<div class="container">
    <div>
        <div class="row">
            @Html.DisplayFor(modelItem => Model.DescricaoLonga)
        </div>
        <hr />
        <br />
        <div class="row">
            <b>Quando:</b><br />
            @Model.DataInicio.ToString("d") até @Model.DataFim.ToString("d")
        </div>
        <br />
        <div class="row">
            <b>Valor:</b><br />
            @{
                if (Model.Gratuito)
                {
                    @Html.DisplayName("Gratuito")
                }
                else
                {
                    @Html.DisplayFor(modelItem => Model.Valor)
                }
            }
        </div>
        <br />
        <div class="row">
            <b>Tipo de Evento:</b><br />
            @{
                var categoria = new CategoriaViewModel().ListarCategorias().FirstOrDefault(c => c.Id == Model.CategoriaId);
                @Html.Raw(categoria.Nome)
            }
        </div>
        <br />
        <div class="row">
            <b>Organizado por:</b><br />
            @Html.DisplayFor(modelItem => Model.NomeEmpresa)
        </div>
        <br />
        <div class="row">
            <b>Onde?</b><br />
            @{
                if (Model.Online)
                {
                    @Html.DisplayName("Evento Online")
                }
                else
                {
                    var endereco = Model.Endereco.ToString();
                    @Html.DisplayName(endereco)
                }
            }
        </div>
        <br />
    </div>

    <div>
        <a href="javascript:history.go(-1)" class="btn btn-info">Voltar</a>
    </div>
</div>

Eventos.IO/src/Eventos.IO.Site/Views/Eventos/Edit.cshtml
@model Eventos.IO.Application.ViewModels.EventoViewModel

@{
    ViewData["Title"] = "Editar Evento";
}

<h2>@ViewData["Title"]</h2>

<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.css" rel="stylesheet">

<h4>Lembre-se que muitas pessoas já podem ter visto este evento antes de mudar datas e etc.</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">

            <vc:summary></vc:summary>

            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="OrganizadorId" />

            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DescricaoLonga" class="control-label"></label>
                <textarea rows="5" asp-for="DescricaoLonga" class="form-control"></textarea>
                <span asp-validation-for="DescricaoLonga" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Categoria" class="control-label"></label>
                @Html.Partial("_Categorias")
                <span asp-validation-for="Categoria" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataInicio" class="control-label"></label>
                <input asp-for="DataInicio" type="text" asp-format="{0:dd/MM/yyyy}" class="form-control" />
                <span asp-validation-for="DataInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataFim" class="control-label"></label>
                <input asp-for="DataFim" type="text" asp-format="{0:dd/MM/yyyy}" class="form-control" />
                <span asp-validation-for="DataFim" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="Gratuito" /> @Html.DisplayNameFor(model => model.Gratuito)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Valor" class="control-label"></label>
                <input asp-for="Valor" class="form-control" />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="Online" /> @Html.DisplayNameFor(model => model.Online)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="NomeEmpresa" class="control-label"></label>
                <input asp-for="NomeEmpresa" class="form-control" />
                <span asp-validation-for="NomeEmpresa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input id="btSubmit" type="submit" value="Atualizar Evento" class="btn btn-success" />
                <a asp-action="MeusEventos" class="btn btn-info">Voltar para a Lista</a>
            </div>
        </form>
    </div>
</div>

<div id="EnderecoForm">
    <div id="EnderecoTarget">
        @Html.Partial("_DetalhesEndereco")
    </div>
</div>

<div id="myModal" class="modal fade in">
    <div class="modal-dialog">
        <div class="modal-content">
            <div id="myModalContent"></div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/locales/bootstrap-datepicker.pt-BR.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/locales/bootstrap-datepicker.pt.min.js"></script>

    <script>
        ValidacoesEvento();
        AjaxModal();
    </script>

    @{
        if (ViewBag.RetornoPost != null)
        {
            var notificacao = ViewBag.RetornoPost.ToString().Split(',');

            <script>
               toastr["@notificacao[0]"]("@notificacao[1]");
            </script>

            if (@notificacao[0] == "success")
            {
                <script>
                    toastr.options.onHidden = function () {
                        window.location = "https://localhost:44381/Eventos/meuseventos";
                    }

                    toastr.options.onclick = function () {
                        window.location = "https://localhost:44381/Eventos/meuseventos";
                    }

                    toastr.options.onCloseClick = function () {
                        window.location = "https://localhost:44381/Eventos/meuseventos";
                    }
                    $("#btSubmit").prop("disabled", true);
                </script>
            }
        }
    }
}

Eventos.IO/src/Eventos.IO.Site/Views/Eventos/Index.cshtml
@model IEnumerable<Eventos.IO.Application.ViewModels.EventoViewModel>

@{
    ViewData["Title"] = "Lista dos Próximos Eventos";
}

<h2>@ViewData["Title"]</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataInicio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataFim)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Valor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Online)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @item.DataInicio.ToString("d")
                </td>
                <td>
                    @item.DataFim.ToString("d")
                </td>
                <td>
                    @{
                        if (item.Gratuito)
                        {
                            @Html.DisplayName("Gratuito")
                        }
                        else
                        {
                            @Html.DisplayFor(modelItem => item.Valor)
                        }
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Online)
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-primary">
                        <span class="glyphicon glyphicon-search"></span>Ver Detalhes
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

Eventos.IO/src/Eventos.IO.Site/Views/Eventos/_AtualizarEndereco.cshtml
@model Eventos.IO.Application.ViewModels.EventoViewModel

@{
    ViewData["Title"] = "Atualizar Endereço";
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">
        <span aria-hidden="true">x</span><span class="sr-only">Fechar</span>
    </button>
    <h4 class="modal-title">@ViewData["Title"]</h4>
</div>

<form asp-action="AtualizarEndereco">
    <div class="modal-body">
        <div class="form-horizontal">
            <vc:summary></vc:summary>

            @Html.Partial("_Endereco")

            <div class="modal-footer">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Atualizar Endereço" class="btn btn-success" />
                    <input type="button" class="btn btn-info" value="Fechar" data-dismiss="modal" />
                </div>
            </div>        
        </div>
    </div>
</form>

Eventos.IO/src/Eventos.IO.Site/Views/Eventos/_Categorias.cshtml
@using Eventos.IO.Application.ViewModels
@model EventoViewModel
@{
    var categorias = (IEnumerable<SelectListItem>) new CategoriaViewModel().Categorias();
}
<select asp-for="CategoriaId" asp-items="@categorias" class="form-control">

</select>

Eventos.IO/src/Eventos.IO.Site/Views/Eventos/_Estados.cshtml
@using Eventos.IO.Application.ViewModels
@model EventoViewModel
@{
    var estados = (IEnumerable<SelectListItem>) new EnderecoViewModel().Estados();
}
<select asp-for="Endereco.Estado" asp-items="@estados" class="form-control">

</select>

Eventos.IO/src/Eventos.IO.Site/Views/Eventos/_IncluirEndereco.cshtml
@model Eventos.IO.Application.ViewModels.EventoViewModel

@{
    ViewData["Title"] = "Incluir Endereço";
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">
        <span aria-hidden="true">x</span><span class="sr-only">Fechar</span>
    </button>
    <h4 class="modal-title">@ViewData["Title"]</h4>
</div>

<form asp-action="IncluirEndereco">
    <div class="modal-body">
        <div class="form-horizontal">
            <vc:summary></vc:summary>

            @Html.Partial("_Endereco")

            <div class="modal-footer">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Atualizar Endereço" class="btn btn-success" />
                    <input type="button" class="btn btn-info" value="Fechar" data-dismiss="modal" />
                </div>
            </div>        
        </div>
    </div>
</form>